//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HOTELRESERVATIONSYSTEM.AppData
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HotelReservationDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HotelReservationDBEntities object using the connection string found in the 'HotelReservationDBEntities' section of the application configuration file.
        /// </summary>
        public HotelReservationDBEntities() : base("name=HotelReservationDBEntities", "HotelReservationDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HotelReservationDBEntities object.
        /// </summary>
        public HotelReservationDBEntities(string connectionString) : base(connectionString, "HotelReservationDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HotelReservationDBEntities object.
        /// </summary>
        public HotelReservationDBEntities(EntityConnection connection) : base(connection, "HotelReservationDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblRole> tblRoles
        {
            get
            {
                if ((_tblRoles == null))
                {
                    _tblRoles = base.CreateObjectSet<tblRole>("tblRoles");
                }
                return _tblRoles;
            }
        }
        private ObjectSet<tblRole> _tblRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblRoom> tblRooms
        {
            get
            {
                if ((_tblRooms == null))
                {
                    _tblRooms = base.CreateObjectSet<tblRoom>("tblRooms");
                }
                return _tblRooms;
            }
        }
        private ObjectSet<tblRoom> _tblRooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblRoomBooked> tblRoomBookeds
        {
            get
            {
                if ((_tblRoomBookeds == null))
                {
                    _tblRoomBookeds = base.CreateObjectSet<tblRoomBooked>("tblRoomBookeds");
                }
                return _tblRoomBookeds;
            }
        }
        private ObjectSet<tblRoomBooked> _tblRoomBookeds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUser> tblUsers
        {
            get
            {
                if ((_tblUsers == null))
                {
                    _tblUsers = base.CreateObjectSet<tblUser>("tblUsers");
                }
                return _tblUsers;
            }
        }
        private ObjectSet<tblUser> _tblUsers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblRoles(tblRole tblRole)
        {
            base.AddObject("tblRoles", tblRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblRooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblRooms(tblRoom tblRoom)
        {
            base.AddObject("tblRooms", tblRoom);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblRoomBookeds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblRoomBookeds(tblRoomBooked tblRoomBooked)
        {
            base.AddObject("tblRoomBookeds", tblRoomBooked);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsers(tblUser tblUser)
        {
            base.AddObject("tblUsers", tblUser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelReservationDBModel", Name="tblRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblRole object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tblRole CreatetblRole(global::System.Int32 id)
        {
            tblRole tblRole = new tblRole();
            tblRole.id = id;
            return tblRole;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelReservationDBModel", Name="tblRoom")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblRoom : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblRoom object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tblRoom CreatetblRoom(global::System.Int32 id)
        {
            tblRoom tblRoom = new tblRoom();
            tblRoom.id = id;
            return tblRoom;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> room_id
        {
            get
            {
                return _room_id;
            }
            set
            {
                Onroom_idChanging(value);
                ReportPropertyChanging("room_id");
                _room_id = StructuralObject.SetValidValue(value, "room_id");
                ReportPropertyChanged("room_id");
                Onroom_idChanged();
            }
        }
        private Nullable<global::System.Int32> _room_id;
        partial void Onroom_idChanging(Nullable<global::System.Int32> value);
        partial void Onroom_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> floor_no
        {
            get
            {
                return _floor_no;
            }
            set
            {
                Onfloor_noChanging(value);
                ReportPropertyChanging("floor_no");
                _floor_no = StructuralObject.SetValidValue(value, "floor_no");
                ReportPropertyChanged("floor_no");
                Onfloor_noChanged();
            }
        }
        private Nullable<global::System.Int32> _floor_no;
        partial void Onfloor_noChanging(Nullable<global::System.Int32> value);
        partial void Onfloor_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_active
        {
            get
            {
                return _is_active;
            }
            set
            {
                Onis_activeChanging(value);
                ReportPropertyChanging("is_active");
                _is_active = StructuralObject.SetValidValue(value, "is_active");
                ReportPropertyChanged("is_active");
                Onis_activeChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_active;
        partial void Onis_activeChanging(Nullable<global::System.Boolean> value);
        partial void Onis_activeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_delete
        {
            get
            {
                return _is_delete;
            }
            set
            {
                Onis_deleteChanging(value);
                ReportPropertyChanging("is_delete");
                _is_delete = StructuralObject.SetValidValue(value, "is_delete");
                ReportPropertyChanged("is_delete");
                Onis_deleteChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_delete;
        partial void Onis_deleteChanging(Nullable<global::System.Boolean> value);
        partial void Onis_deleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tdt
        {
            get
            {
                return _tdt;
            }
            set
            {
                OntdtChanging(value);
                ReportPropertyChanging("tdt");
                _tdt = StructuralObject.SetValidValue(value, "tdt");
                ReportPropertyChanged("tdt");
                OntdtChanged();
            }
        }
        private Nullable<global::System.DateTime> _tdt;
        partial void OntdtChanging(Nullable<global::System.DateTime> value);
        partial void OntdtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> udt
        {
            get
            {
                return _udt;
            }
            set
            {
                OnudtChanging(value);
                ReportPropertyChanging("udt");
                _udt = StructuralObject.SetValidValue(value, "udt");
                ReportPropertyChanged("udt");
                OnudtChanged();
            }
        }
        private Nullable<global::System.DateTime> _udt;
        partial void OnudtChanging(Nullable<global::System.DateTime> value);
        partial void OnudtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ddt
        {
            get
            {
                return _ddt;
            }
            set
            {
                OnddtChanging(value);
                ReportPropertyChanging("ddt");
                _ddt = StructuralObject.SetValidValue(value, "ddt");
                ReportPropertyChanged("ddt");
                OnddtChanged();
            }
        }
        private Nullable<global::System.DateTime> _ddt;
        partial void OnddtChanging(Nullable<global::System.DateTime> value);
        partial void OnddtChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelReservationDBModel", Name="tblRoomBooked")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblRoomBooked : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblRoomBooked object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tblRoomBooked CreatetblRoomBooked(global::System.Int32 id)
        {
            tblRoomBooked tblRoomBooked = new tblRoomBooked();
            tblRoomBooked.id = id;
            return tblRoomBooked;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value, "user_id");
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int32> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int32> value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> room_id
        {
            get
            {
                return _room_id;
            }
            set
            {
                Onroom_idChanging(value);
                ReportPropertyChanging("room_id");
                _room_id = StructuralObject.SetValidValue(value, "room_id");
                ReportPropertyChanged("room_id");
                Onroom_idChanged();
            }
        }
        private Nullable<global::System.Int32> _room_id;
        partial void Onroom_idChanging(Nullable<global::System.Int32> value);
        partial void Onroom_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> check_in_date
        {
            get
            {
                return _check_in_date;
            }
            set
            {
                Oncheck_in_dateChanging(value);
                ReportPropertyChanging("check_in_date");
                _check_in_date = StructuralObject.SetValidValue(value, "check_in_date");
                ReportPropertyChanged("check_in_date");
                Oncheck_in_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _check_in_date;
        partial void Oncheck_in_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncheck_in_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> check_out_date
        {
            get
            {
                return _check_out_date;
            }
            set
            {
                Oncheck_out_dateChanging(value);
                ReportPropertyChanging("check_out_date");
                _check_out_date = StructuralObject.SetValidValue(value, "check_out_date");
                ReportPropertyChanged("check_out_date");
                Oncheck_out_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _check_out_date;
        partial void Oncheck_out_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncheck_out_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> check_in_time
        {
            get
            {
                return _check_in_time;
            }
            set
            {
                Oncheck_in_timeChanging(value);
                ReportPropertyChanging("check_in_time");
                _check_in_time = StructuralObject.SetValidValue(value, "check_in_time");
                ReportPropertyChanged("check_in_time");
                Oncheck_in_timeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _check_in_time;
        partial void Oncheck_in_timeChanging(Nullable<global::System.TimeSpan> value);
        partial void Oncheck_in_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Check_out_time
        {
            get
            {
                return _Check_out_time;
            }
            set
            {
                OnCheck_out_timeChanging(value);
                ReportPropertyChanging("Check_out_time");
                _Check_out_time = StructuralObject.SetValidValue(value, "Check_out_time");
                ReportPropertyChanged("Check_out_time");
                OnCheck_out_timeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Check_out_time;
        partial void OnCheck_out_timeChanging(Nullable<global::System.TimeSpan> value);
        partial void OnCheck_out_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_active
        {
            get
            {
                return _is_active;
            }
            set
            {
                Onis_activeChanging(value);
                ReportPropertyChanging("is_active");
                _is_active = StructuralObject.SetValidValue(value, "is_active");
                ReportPropertyChanged("is_active");
                Onis_activeChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_active;
        partial void Onis_activeChanging(Nullable<global::System.Boolean> value);
        partial void Onis_activeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_delete
        {
            get
            {
                return _is_delete;
            }
            set
            {
                Onis_deleteChanging(value);
                ReportPropertyChanging("is_delete");
                _is_delete = StructuralObject.SetValidValue(value, "is_delete");
                ReportPropertyChanged("is_delete");
                Onis_deleteChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_delete;
        partial void Onis_deleteChanging(Nullable<global::System.Boolean> value);
        partial void Onis_deleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_booked
        {
            get
            {
                return _is_booked;
            }
            set
            {
                Onis_bookedChanging(value);
                ReportPropertyChanging("is_booked");
                _is_booked = StructuralObject.SetValidValue(value, "is_booked");
                ReportPropertyChanged("is_booked");
                Onis_bookedChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_booked;
        partial void Onis_bookedChanging(Nullable<global::System.Boolean> value);
        partial void Onis_bookedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> delete_datetime
        {
            get
            {
                return _delete_datetime;
            }
            set
            {
                Ondelete_datetimeChanging(value);
                ReportPropertyChanging("delete_datetime");
                _delete_datetime = StructuralObject.SetValidValue(value, "delete_datetime");
                ReportPropertyChanged("delete_datetime");
                Ondelete_datetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _delete_datetime;
        partial void Ondelete_datetimeChanging(Nullable<global::System.DateTime> value);
        partial void Ondelete_datetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> cancel_datetime
        {
            get
            {
                return _cancel_datetime;
            }
            set
            {
                Oncancel_datetimeChanging(value);
                ReportPropertyChanging("cancel_datetime");
                _cancel_datetime = StructuralObject.SetValidValue(value, "cancel_datetime");
                ReportPropertyChanged("cancel_datetime");
                Oncancel_datetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _cancel_datetime;
        partial void Oncancel_datetimeChanging(Nullable<global::System.DateTime> value);
        partial void Oncancel_datetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> approved_by
        {
            get
            {
                return _approved_by;
            }
            set
            {
                Onapproved_byChanging(value);
                ReportPropertyChanging("approved_by");
                _approved_by = StructuralObject.SetValidValue(value, "approved_by");
                ReportPropertyChanged("approved_by");
                Onapproved_byChanged();
            }
        }
        private Nullable<global::System.Int32> _approved_by;
        partial void Onapproved_byChanging(Nullable<global::System.Int32> value);
        partial void Onapproved_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> approved_datetime
        {
            get
            {
                return _approved_datetime;
            }
            set
            {
                Onapproved_datetimeChanging(value);
                ReportPropertyChanging("approved_datetime");
                _approved_datetime = StructuralObject.SetValidValue(value, "approved_datetime");
                ReportPropertyChanged("approved_datetime");
                Onapproved_datetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _approved_datetime;
        partial void Onapproved_datetimeChanging(Nullable<global::System.DateTime> value);
        partial void Onapproved_datetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remarks
        {
            get
            {
                return _remarks;
            }
            set
            {
                OnremarksChanging(value);
                ReportPropertyChanging("remarks");
                _remarks = StructuralObject.SetValidValue(value, true, "remarks");
                ReportPropertyChanged("remarks");
                OnremarksChanged();
            }
        }
        private global::System.String _remarks;
        partial void OnremarksChanging(global::System.String value);
        partial void OnremarksChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelReservationDBModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUser object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tblUser CreatetblUser(global::System.Int32 id)
        {
            tblUser tblUser = new tblUser();
            tblUser.id = id;
            return tblUser;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> role_id
        {
            get
            {
                return _role_id;
            }
            set
            {
                Onrole_idChanging(value);
                ReportPropertyChanging("role_id");
                _role_id = StructuralObject.SetValidValue(value, "role_id");
                ReportPropertyChanged("role_id");
                Onrole_idChanged();
            }
        }
        private Nullable<global::System.Int32> _role_id;
        partial void Onrole_idChanging(Nullable<global::System.Int32> value);
        partial void Onrole_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_active
        {
            get
            {
                return _is_active;
            }
            set
            {
                Onis_activeChanging(value);
                ReportPropertyChanging("is_active");
                _is_active = StructuralObject.SetValidValue(value, "is_active");
                ReportPropertyChanged("is_active");
                Onis_activeChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_active;
        partial void Onis_activeChanging(Nullable<global::System.Boolean> value);
        partial void Onis_activeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_deleted
        {
            get
            {
                return _is_deleted;
            }
            set
            {
                Onis_deletedChanging(value);
                ReportPropertyChanging("is_deleted");
                _is_deleted = StructuralObject.SetValidValue(value, "is_deleted");
                ReportPropertyChanged("is_deleted");
                Onis_deletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_deleted;
        partial void Onis_deletedChanging(Nullable<global::System.Boolean> value);
        partial void Onis_deletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tdt
        {
            get
            {
                return _tdt;
            }
            set
            {
                OntdtChanging(value);
                ReportPropertyChanging("tdt");
                _tdt = StructuralObject.SetValidValue(value, "tdt");
                ReportPropertyChanged("tdt");
                OntdtChanged();
            }
        }
        private Nullable<global::System.DateTime> _tdt;
        partial void OntdtChanging(Nullable<global::System.DateTime> value);
        partial void OntdtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> udt
        {
            get
            {
                return _udt;
            }
            set
            {
                OnudtChanging(value);
                ReportPropertyChanging("udt");
                _udt = StructuralObject.SetValidValue(value, "udt");
                ReportPropertyChanged("udt");
                OnudtChanged();
            }
        }
        private Nullable<global::System.DateTime> _udt;
        partial void OnudtChanging(Nullable<global::System.DateTime> value);
        partial void OnudtChanged();

        #endregion

    }

    #endregion

}
